# Generated by Django 4.2 on 2023-04-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date', models.DateField(auto_now=True)),
                ('excerpt', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('main_image', models.ImageField(null=True, upload_to='news')),
                ('additional_image1', models.ImageField(null=True, upload_to='news')),
                ('additional_image2', models.ImageField(null=True, upload_to='news')),
            ],
        ),
    ]
