# Generated by Django 4.2 on 2023-04-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='additional_image1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='additional_image2',
        ),
    ]
