# Generated by Django 4.2 on 2023-04-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0002_remove_news_additional_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='main_image',
            new_name='preview_image',
        ),
        migrations.AddField(
            model_name='news',
            name='detail_image',
            field=models.ImageField(null=True, upload_to='news'),
        ),
    ]
