# Generated by Django 4.2 on 2023-05-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0003_rename_main_image_news_preview_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureReleases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('developer', models.CharField(max_length=80)),
                ('release_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='future_releases')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
