# Generated by Django 4.2 on 2023-05-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0004_futurereleases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurereleases',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
