# Generated by Django 4.2 on 2023-05-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0005_alter_futurereleases_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurereleases',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
