# Generated by Django 4.2 on 2023-05-03 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0006_alter_futurereleases_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='top_games')),
                ('slug', models.SlugField(unique=True)),
                ('my_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.AlterField(
            model_name='futurereleases',
            name='developer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='futurereleases',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
