# Generated by Django 4.2 on 2023-05-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0008_topgames_rating_count_topgames_total_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topgames',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='topgames',
            name='total_rating',
        ),
        migrations.DeleteModel(
            name='GameRating',
        ),
    ]
