# Generated by Django 4.2 on 2023-05-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0010_userrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topgames',
            name='my_rating',
        ),
        migrations.AddField(
            model_name='topgames',
            name='user_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
