# Generated by Django 4.2 on 2023-05-05 09:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_hub', '0012_remove_topgames_user_rating_topgames_my_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topgames',
            name='my_rating',
        ),
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_hub.topgames')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='topgames',
            name='ratings',
            field=models.ManyToManyField(through='games_hub.GameRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
