# Generated by Django 4.2 on 2023-05-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0013_remove_topgames_my_rating_gamerating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topgames',
            name='trailer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
