# Generated by Django 4.2 on 2023-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0014_topgames_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurereleases',
            name='trailer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
