# Generated by Django 4.2 on 2023-05-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0021_rename_description_topgames_description_part1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurereleases',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
