# Generated by Django 4.2 on 2023-05-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0022_futurereleases_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futurereleases',
            old_name='description',
            new_name='description_part1',
        ),
        migrations.AddField(
            model_name='futurereleases',
            name='description_part2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
