# Generated by Django 4.2 on 2023-05-22 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_hub', '0023_rename_description_futurereleases_description_part1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurereleases',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
