# Generated by Django 4.2 on 2023-06-06 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_hub', '0024_futurereleases_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_ratings', to='games_hub.topgames'),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
