# Generated by Django 4.2 on 2023-06-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0025_alter_gamerating_game_alter_gamerating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerating',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
