# Generated by Django 4.2 on 2023-06-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub', '0027_alter_gamerating_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.CharField(max_length=44),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=24),
        ),
    ]
